Upgraded NetApp Files SDK version to latest 1.13.0
Azure-Samples/netappfiles-dotnetcore-pool-change-sdk-sample pull request #3
Opened 2021-09-03 15:44 UTC by AdelGhabboun

1. Upgraded NetApp Files SDK version to 1.13.0
2. Upgraded target framework to .NET 5.0

2021-09-08 11:36 UTC, hildurhodd approved these changes
LGTM

2021-09-15 15:55 UTC, paulomarquesc commented on CHANGELOG.md
> +[1.0.1 (2019-10-09)](#1.0.1 (2021-09-02))
>2019-10-09 [](http://example.com/codeflow?start=8&length=10)

Date here needs to be updated

2021-09-15 15:55 UTC, paulomarquesc requested changes
:clock1:

2021-09-15 20:54 UTC, paulomarquesc approved these changes
:shipit:

2021-09-15 21:05 UTC, merged